# Generated by Django 3.0.3 on 2021-08-18 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Compaign",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=200)),
                ("GPS", models.CharField(default="", max_length=50)),
                ("daira", models.CharField(default="", max_length=50)),
                ("baladia", models.CharField(default="", max_length=50)),
                ("image_url", models.CharField(default="", max_length=50)),
                (
                    "association",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Need",
            fields=[
                ("name", models.CharField(max_length=50, null=True)),
                ("description", models.CharField(blank=True, max_length=200, null=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("_id", models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                ("name", models.CharField(max_length=50, null=True)),
                ("description", models.CharField(blank=True, max_length=200, null=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("_id", models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="Wilaya",
            fields=[
                ("number", models.IntegerField(null=True)),
                ("name", models.CharField(max_length=50, null=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("_id", models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="Step",
            fields=[
                ("name", models.CharField(max_length=50, null=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("_id", models.AutoField(editable=False, primary_key=True, serialize=False)),
                ("type", models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="base.Type")),
            ],
        ),
        migrations.CreateModel(
            name="PersonProfile",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("firstname", models.CharField(max_length=50)),
                ("lastname", models.CharField(max_length=50)),
                ("phone", models.CharField(default="", max_length=50)),
                ("dateOfBirth", models.DateTimeField(default="")),
                ("profession", models.CharField(default="", max_length=50)),
                ("wilaya", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=200)),
                ("address2", models.CharField(blank=True, max_length=200)),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompaignSteps",
            fields=[
                ("description", models.CharField(default="", max_length=200)),
                ("range", models.IntegerField(null=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("_id", models.AutoField(editable=False, primary_key=True, serialize=False)),
                ("compaign", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="base.Compaign")),
                ("step", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="base.Step")),
            ],
        ),
        migrations.CreateModel(
            name="CompaignNeeds",
            fields=[
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("_id", models.AutoField(editable=False, primary_key=True, serialize=False)),
                ("compaign", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="base.Compaign")),
                ("need", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="base.Need")),
            ],
        ),
        migrations.AddField(
            model_name="compaign",
            name="type",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="base.Type"),
        ),
        migrations.AddField(
            model_name="compaign",
            name="wilaya",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="base.Wilaya"),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("title", models.CharField(max_length=50, null=True)),
                ("payload", models.CharField(blank=True, max_length=200, null=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("_id", models.AutoField(editable=False, primary_key=True, serialize=False)),
                ("compaign", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="base.Compaign")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="AssociationWilayas",
            fields=[
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("_id", models.AutoField(editable=False, primary_key=True, serialize=False)),
                (
                    "association",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("wilaya", models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="base.Wilaya")),
            ],
        ),
        migrations.CreateModel(
            name="AssociationProfile",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("phone", models.CharField(default="", max_length=50)),
                ("fax", models.CharField(default="", max_length=50)),
                ("name", models.CharField(max_length=50)),
                ("activity", models.CharField(max_length=200)),
                ("associationNumber", models.CharField(max_length=200)),
                ("logo", models.CharField(default="", max_length=50)),
                ("baseWilaya", models.CharField(max_length=50)),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
