# Generated by Django 3.0.3 on 2021-08-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compaignneeds',
            name='qte',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='compaignneeds',
            name='qteDonated',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='compaignsteps',
            name='isDone',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
