# Generated by Django 3.0.3 on 2021-08-19 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210819_0745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compaignneeds',
            name='qte',
        ),
        migrations.RemoveField(
            model_name='compaignneeds',
            name='qteDonated',
        ),
        migrations.RemoveField(
            model_name='compaignsteps',
            name='isDone',
        ),
    ]
