# Generated by Django 3.0.3 on 2021-08-19 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210819_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personprofile',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='personprofile',
            name='lastname',
        ),
    ]
