# Generated by Django 3.2.6 on 2021-08-20 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0006_auto_20210819_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('name', models.CharField(default='', max_length=50)),
                ('acronym', models.CharField(blank=True, max_length=5)),
                ('isFloat', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='associationprofile',
            name='_id',
        ),
        migrations.RemoveField(
            model_name='associationwilayas',
            name='_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='_id',
        ),
        migrations.RemoveField(
            model_name='compaign',
            name='_id',
        ),
        migrations.RemoveField(
            model_name='compaign',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='compaignneeds',
            name='_id',
        ),
        migrations.RemoveField(
            model_name='compaignneeds',
            name='qte',
        ),
        migrations.RemoveField(
            model_name='compaignsteps',
            name='_id',
        ),
        migrations.RemoveField(
            model_name='need',
            name='_id',
        ),
        migrations.RemoveField(
            model_name='personprofile',
            name='_id',
        ),
        migrations.RemoveField(
            model_name='step',
            name='_id',
        ),
        migrations.RemoveField(
            model_name='type',
            name='_id',
        ),
        migrations.RemoveField(
            model_name='wilaya',
            name='_id',
        ),
        migrations.AddField(
            model_name='associationprofile',
            name='coverImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='associationprofile',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='associationprofile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='associationprofile',
            name='twitter',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='associationwilayas',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='compaign',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='compaign',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compaign',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='compaign',
            name='imageUrl',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='compaign',
            name='isArchived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compaign',
            name='isDone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compaign',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='compaign',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compaignneeds',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='compaignneeds',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='compaignneeds',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='compaignneeds',
            name='qteAccepted',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='compaignneeds',
            name='qteRequested',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='compaignsteps',
            name='completeDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compaignsteps',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='need',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='personprofile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='personprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='personprofile',
            name='isMale',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='step',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='type',
            name='coverImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='type',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='wilaya',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='associationprofile',
            name='baseWilaya',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.wilaya'),
        ),
        migrations.AlterField(
            model_name='associationprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='associationprofile',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='compaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.compaign'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='compaign',
            name='GPS',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='compaign',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='compaign',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='compaignneeds',
            name='compaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.compaign'),
        ),
        migrations.AlterField(
            model_name='compaignneeds',
            name='need',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.need'),
        ),
        migrations.AlterField(
            model_name='compaignneeds',
            name='qteDonated',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='compaignsteps',
            name='compaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.compaign'),
        ),
        migrations.AlterField(
            model_name='compaignsteps',
            name='isDone',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='compaignsteps',
            name='range',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='compaignsteps',
            name='step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.step'),
        ),
        migrations.AlterField(
            model_name='need',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='need',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='address2',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='profession',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='wilaya',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.wilaya'),
        ),
        migrations.AlterField(
            model_name='step',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='type',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='wilaya',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='wilaya',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='PersonDonation',
            fields=[
                ('qte', models.FloatField(default=1)),
                ('status', models.FloatField(default=1)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('compaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.compaign')),
                ('need', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.need')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonCompaignReaction',
            fields=[
                ('isLike', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('compaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.compaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('message', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='need',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.unit'),
        ),
    ]
