# Generated by Django 3.0.3 on 2021-08-25 14:24

import base.constants.donation_status
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20210820_0906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compaign',
            old_name='imageUrl',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='persondonation',
            old_name='qte',
            new_name='qteDonated',
        ),
        migrations.RemoveField(
            model_name='persondonation',
            name='need',
        ),
        migrations.AddField(
            model_name='persondonation',
            name='compaignNeed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.CompaignNeeds'),
        ),
        migrations.AddField(
            model_name='persondonation',
            name='qteAccepted',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='persondonation',
            name='qteDelivered',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='persondonation',
            name='status',
            field=models.IntegerField(default=base.constants.donation_status.DonationStatus['wait']),
        ),
    ]
